### ISSUE TITLE
Empty Command and Ambiguous Use of Command

### ISSUE THREAD

**Issue by MostlyKIGuess** [jellydn/CopilotChat.nvim#38]
- I saw the other thread which talked about this but I can not seem to find a solution
- I am using NVChad on linux and I can not do remoteupdateplugins and I just installed it via lazy, can't seem to figure out what's wrong with that?

**Comment by MostlyKIGuess** [comment]
Error executing Lua callback: vim/_editor.lua:0: nvim_exec2(): Vim:E464: Ambiguous use of user-defined command: CopilotChat Explain how it works.                           
stack traceback:                                                                                                                                                                    
        [C]: in function 'nvim_exec2'                                                                                                                                               
        vim/_editor.lua: in function 'cmd'                                                                                                                                          
        ...hare/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/init.lua:23: in function <...hare/nvim/lazy/CopilotChat.nvim/lua/CopilotChat/init.lua:22>       
        
        this is the error I get when I run any command

**Comment by AnthonyUtt** [comment]
Also using NVChad on NixOS and having the exact same error. I have the `CopilotChatExplain` and `CopilotChatTests` commands available, but not `CopilotChat` or any of the other commands. This issue seems to occur on both the main branch and on `canary`.

I tried running `:checkhealth` and I was seeing some issues with Python deps, but now I am not seeing an entry for this plugin at all?

Here is my entry for Lazy.nvim:
```lua
  {
    "jellydn/CopilotChat.nvim",
    branch = "canary",
    cmd = {
      "CopilotChat",
      "CopilotChatExplain",
      "CopilotChatTests",
      "CopilotChatReview",
      "CopilotChatRefactor",
      "CopilotChatSummarize",
      "CopilotChatSpelling",
      "CopilotChatWording",
      "CopilotChatConcise",
      "CopilotChatVsplitVisual",
      "CopilotChatInPlace",
      "UpdateRemotePlugins",
    },
    event = "VeryLazy",
    opts = {
      mode = "split",
    },
    init = function()
      require("core.utils").load_mappings "copilotchat"
    end,
    build = function()
      vim.defer_fn(function()
        vim.cmd("UpdateRemotePlugins")
        vim.notify("CopilotChat - Updated remote plugins. Please restart Neovim.")
      end, 3000)
    end,
  },
```
and my Nvim nix setup:
```nix
{ config, pkgs, lib, ... }:
let
  pythonDeps = pkgs.python311.withPackages (ps: with ps; [
    python-dotenv
    requests
    pynvim
    prompt-toolkit
    tiktoken
  ]);
in
{
  programs.neovim = {
    enable = true;
    viAlias = true;
    vimAlias = true;
    extraPackages = with pkgs; [
      pythonDeps
    ];
  };
}
```

**Comment by MostlyKIGuess** [comment]
Wait umm I think I am onto something, I saw the original python code alright and it says 0.9.2 for nvim version, what's your nvim?

Is it 0.10.0?

**Comment by AnthonyUtt** [comment]
My nvim version is 0.9.5

**Comment by jellydn** [comment]
Did you run as those steps?
 
3. Run :UpdateRemotePlugins
4. Restart neovim

The CopilotChat is written in Python so you need to run above command to use. Let me know if that works. Thanks for your reporting.

**Comment by MostlyKIGuess** [comment]
I am not able to run UpdateRemotePlugins it just says
not an editor commands

**Comment by jellydn** [comment]
If so, I think this might help you https://github.com/neovim/neovim/issues/13267

**Comment by MostlyKIGuess** [comment]
Alright  I did that and it says:
unction remote#host#UpdateRemotePlugins[6]..<SNR>37_RegistrationCommands[15]..remote#host#Require, line 10                               
Vim(let):E117: Unknown function: provider#python3#Require                                                                                         
remote/host: generated rplugin manifest: /home/mostlyk/.local/share/nvim/rplugin.vim

**Comment by MostlyKIGuess** [comment]
Mb it was my config problem.

**Comment by siduck** [comment]
for those not able to get remoteplugin command work, just enable it in your chadrc's lazy_nvim table

```lua
local M = {}

local disabled_plugins = require("plugins.configs.lazy_nvim").performance.rtp.disabled_plugins

M.ui = {
  theme = "one_light",
}

M.plugins = "custom.plugins"

M.lazy_nvim = {
  performance = {
    rtp = {
      disabled_plugins = vim.tbl_filter(function(x)
        return x ~= "rplugin"
      end, disabled_plugins),
    },
  },
}

M.mappings = require "custom.mappings"

return M
```
